server:
  port: 9099

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka
      
spring:
  application:
    name: gateway-service
    
  cloud:
    gateway:
      routes:
      - id: gallery-service
        uri: lb://GALLERY-SERVICE
        predicates:
        - Path=/galleries/**
        
      - id: image-service
        uri: lb://IMAGE-SERVICE
        predicates:
        - Path=/images/**
        
      - id: auth-service
        uri: lb://AUTH-SERVICE
        predicates:
        - Path=/auth/**
 
      default-filters:
        - Authentication 
        
jwt:
   secret: ZXhhbXBsZS1zZWNyZXQ=