spring:
  application:
    name: auth-service

server:
  port: 9100

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka

### JWT data
jwt:
  secret: fRtN+gqw19bm1u/TXmWBEnr8DshGX0LUPRZzUgu1Xoyl298ekkmNOUIcifx1yMT18HzHwtp8LwqiCNR5OyF+BA==
  token:
    validity: 60000
