spring:
  application:
    name: user-service

    data:
      mongodb:
        host: localhost
        port: 27017
        database: microservices-git
        authentication-database: admin
        username: root
        password: 123456

server:
  port: 9101

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka


